
library:
directory:
plugins:
pluginpath: ~/.config/beets/plugins
ignore:
replace:

threaded: yes
ui:
  color: yes
  colors:
    text_success: green
    text_warning: yellow
    text_error: red
    text_highlight: red
    text_highlight_minor: lightgray
    action_default: turquoise
    action: blue
log: ~/var/log/beets.log
paths:
  default:
  singleton:
  comp:
zero:
  fields: comments
lyrics:
  fallback: 'No lyrics found'
